spring:
  application:
    name: springRedisApplication
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/spring?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: 12345
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 6

debug: true