spring:
  application:
    name: es
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/susan?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  data:
    elasticsearch:
      schema: https
      cluster-name: elasticsearch
      cluster-nodes: localhost:9200 #可配置多个
      connection-req-time-out: 20000
      socket-time-out: 30000
      connection-time-out: 20000
      user_name: elastic
      password: _Td8m1AZJm-wlw_=fO74

